{% set name = "cyeva" %}
{% set version = "0.1.0.beta.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/caiyunapp/cyeva/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3b2e77644b8f59308dd0069165215ce812b7c914927411697ea4179e6dec76fd

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.19.5
    - pandas >=1.1.5
    - fire >=0.4.0
    - scipy >=1.5.4
    - pint ==0.18

test:
  imports:
    - cyeva
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/caiyunapp/cyeva
  summary: cyeva is a Python open source tool library to evaluate the accuracy of weather forecast.
  description: |
    cyeva is a Python open source tool library to evaluate the accuracy of weather forecast. 
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/caiyunapp/cyeva

extra:
  recipe-maintainers:
    - caiyunapp
    - Clarmy
